name: Glossing Users Deploy
on: 
  push:
    branches:
      main
jobs:
    deploy:
      strategy: 
        matrix:
            node-version: [21]
            machines: [vlcdhprdp01]
      runs-on: ${{ matrix.machines }}
      steps:
        - uses: actions/checkout@v3
        - run: |
            if [[ ! -e /srv/node/logs/glossing_users.txt ]]; then
                mkdir -p /srv/node/logs
                touch /srv/node/logs/glossing_users.txt
            fi
            cd /srv/node/glossing-users/
            pm2 stop glossing_users
            git stash
            git pull
            npm install
            pm2 start -i max bin/glossing_users.js
